### ISSUE TITLE
Clean your code

### ISSUE THREAD

**Issue by akbarjondev** [abdulatifkhan/bozorlik#2]
https://github.com/abdulatifkhan/bozorlik/blob/ff07aee1f14ec8234d559b28394f82a1c8931830/js/scripts.js#L30

You can keep your codes clean, it's free )

**Comment by abdulatifkhan** [comment]
Free stuff is worthless

**Comment by abdulatifkhan** [comment]
> https://github.com/abdulatifkhan/bozorlik/blob/ff07aee1f14ec8234d559b28394f82a1c8931830/js/scripts.js#L30
> 
> You can keep your codes clean, it's free )

Free stuff is worthless
