### ISSUE TITLE
Ro'yxatdagi elementni tekshirishda xatolik

### ISSUE THREAD

**Issue by udilbar** [abdulatifkhan/bozorlik#3]
![Screenshot_7](https://user-images.githubusercontent.com/68459485/98665204-2b4ff580-236d-11eb-8e59-b6c9d0f48cab.png)
Ro'yaxtda element mavjud yoki mavjud emasligini tekshirish to'g'ri ishlamayapti. Shuni to'g'irlashimiz kerak )

**Comment by abdulatifkhan** [comment]
> ![Screenshot_7](https://user-images.githubusercontent.com/68459485/98665204-2b4ff580-236d-11eb-8e59-b6c9d0f48cab.png)
> Ro'yaxtda element mavjud yoki mavjud emasligini tekshirish to'g'ri ishlamayapti. Shuni to'g'irlashimiz kerak )

Muammoni bartaraf etdik, e'tibor uchun rahmat!)

![image](https://user-images.githubusercontent.com/68887519/98774425-cc41bd80-240c-11eb-8136-483e0745fd8a.png)
